### PR TITLE
Use browserify-package-json

### PR DESCRIPTION
**Pull request by fanatid**
browserify-package-json on [npm](https://www.npmjs.com/package/browserify-package-json) and [github](https://github.com/fanatid/browserify-package-json)

### CODE REVIEW

**Comment by nolanlawson** [comment]
Added a Travis config so this can be automated, but tested manually and tests pass. Thank you!

**Comment by nolanlawson** [comment]
8d81e5d61535566a80ae3bd660620b76d39c1ac9

**Comment by fanatid** [comment]
Thank you! I added you to collaborators on npm and github.

**Comment by nolanlawson** [comment]
Thanks! That’s kind of you, but I’m super swamped with other projects right now, so I’ll have to decline unfortunately.

**Pull request closed without merging**
